/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:36097fd9-e2e2-4908-ba53-d8b302eb7b14",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_teMarUIDB",
    "aws_user_pools_web_client_id": "70vsvgft7rk6f11c6hurm3t0n3",
    "oauth": {
        "domain": "educloudfrontend16c2439c-16c2439c-cleanenv.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:5173/",
        "redirectSignOut": "http://localhost:5173/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "educloudfrontend2bf38c8bc5dc4051a5746eb0aace1a63c289-cleanenv",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
